org: i2pir
app: serverless-test
service: serverless-test

frameworkVersion: '3'

plugins:

provider:
  name: aws
  region: us-west-1
  runtime: nodejs18.x

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
